name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }} 
        key: ${{ secrets.EC2_KEY }}
        script: |
          # go to app folder (create if missing)
          cd ~/app || mkdir ~/app && cd ~/app

          # pull latest code
          if [ -d .git ]; then
            git reset --hard
            git pull
          else
            git clone https://github.com/Tomiwa-S/cicd.git .
          fi

          # setup venv if missing
          if [ ! -d "venv" ]; then
            sudo apt update
            sudo apt install python3.12-venv -y
            python3 -m venv venv
          fi
          
          source venv/bin/activate
          
          # install requirements
          pip install --upgrade pip
          pip install flask gunicorn

          # stop old gunicorn processes (comprehensive cleanup)
          echo "Stopping any existing gunicorn processes..."
          
          # Kill user processes
          # pkill -f gunicorn || true
          
          # Kill any sudo processes
          sudo pkill -f gunicorn || true
          
          # Double-check with more aggressive killing if needed
          sudo pkill -9 -f gunicorn || true
          
          # Wait for processes to fully stop
          sleep 5

          # Simple, reliable approach - just start the process and exit
          echo "Starting gunicorn on port 8000..."
          
          # Start gunicorn in the most reliable way
          setsid bash -c 'cd ~/app && source venv/bin/activate && exec venv/bin/gunicorn -b 0.0.0.0:8000 app:app --access-logfile access.log --error-logfile error.log --daemon' < /dev/null &
          
          echo "🎉 Deployment completed! Process started."
          echo "ℹ️  Check status with: ssh into server and run 'ps aux | grep gunicorn'"
          echo "ℹ️  Check logs with: ssh into server and run 'cd ~/app && tail -f error.log'"